version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      dockerfile_inline: |
        FROM php:8-fpm
        RUN docker-php-source extract \
          && docker-php-ext-install -j$(nproc) pdo_mysql \
          && docker-php-ext-enable pdo_mysql \
          && docker-php-source delete
    volumes:
      - ./:/var/www/html
    links:
      - mysql-db
  mysql-db:
    user: 501:20
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - /mnt/roman/Documents/Projects/mysql-dev:/var/lib/mysql
